---
title: "info_theory"
author: "Benjamin Panny"
date: "`r Sys.Date()`"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
p <- seq(0.001, 1, by = .001)
inf <- tibble(p = p, surprise = -log(p))
inf %>% 
  ggplot(aes(x = p, y = surprise)) +
  geom_line()
```


```{r}
p <- seq(0.001, .999, by = .001)
inf <- tibble(p = p, entropy = -p*log(p)-(1-p)*log(1-p))
inf %>% 
  ggplot(aes(x = p, y = entropy)) +
  geom_line()
```



```{r}
step_size <- 0.01
generate_triplets_no_zeros <- function(step_size) {
  triplets <- expand.grid(a = seq(step_size, 1 - 2 * step_size, by = step_size),
                          b = seq(step_size, 1 - 2 * step_size, by = step_size)) %>%
    rowwise() %>%
    mutate(c = 1 - a - b) %>%
    filter(c > 0)
  
  return(as.matrix(triplets[, c("a", "b", "c")]))
}

entropy <- function(p) {
  -sum(p * log2(p))
}

triplets <- generate_triplets_no_zeros(step_size)
entropies <- apply(triplets, 1, entropy)

dat <- tibble(p1 = triplets[, 'a'], p2 = triplets[, 'b'], p3 = triplets[, 'c'], entropy = entropies)

# Plot
ggplot(dat, aes(x = p1, y = p2, fill = entropy)) +
  geom_raster() +
  scale_fill_gradient(low = "purple", high = "lightblue", name = "Entropy") +
  labs(x = "Probability 1 (p1)", y = "Probability 2 (p2)", title = "Entropy of Probability Triplets") +
  theme_minimal() +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())
```


$$
H(X) = -\sum_{k=1}^n p_k \log(p_k) \\
\text{For equal probabilities} \\
\begin{align}
H(X) &= -\sum_{k=1}^n \frac{1}{n} \log(\frac{1}{n}) \\
&= -n \left(\frac{1}{n} \log(\frac{1}{n}) \right) \\
&= - \log(\frac{1}{n})
\end{align}
$$


```{r}
# Simplified and optimized entropy calculation for equal probability outcomes
equal_outcome_entropy <- function(n) {
  -log(1/n)
}

# Creating a tibble with n values
eq_dat <- tibble(n = seq(1, 1e3, 1))

# Vectorized computation of entropies
eq_dat$entropies <- equal_outcome_entropy(eq_dat$n)
```

```{r}
eq_dat %>% 
  ggplot(aes(x = n, y = entropies)) +
  geom_line()
```


