---
title: "seir_models"
author: "Benjamin Panny"
date: "`r Sys.Date()`"
output: 
  html_document:
    code_folding: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

# Define the SEIR model
seir_model <- function(time, state, parameters) {
  with(as.list(c(state, parameters)), {
    dS <- -beta * S * I
    dE <- beta * S * I - sigma * E
    dI <- sigma * E - gamma * I
    dR <- gamma * I
    return(list(c(dS, dE, dI, dR)))
  })
}

par(las=F)
# Initial state and parameters
initial_state <- c(S = 999, E = 1, I = 0, R = 0)
parameters <- c(beta = 0.001, sigma = 0.1, gamma = 0.1)
times <- seq(0, 100, by = 1)

# Solve the model
output <- ode(y = initial_state, times = times, func = seir_model, parms = parameters)

# Convert output to a data frame
output_df <- as.data.frame(output)

# Reshape for ggplot2
output_melted <- melt(output_df, id.vars = "time")

# Plot using ggplot2
ggplot(output_melted, aes(x = time, y = value, color = variable)) +
  geom_line() +
  labs(x = "Time", y = "Number of Individuals", color = "Compartment") +
  ggtitle("SEIR Model") +
  theme_minimal()
```


```{r}
# Define the SEEIR model
seeir_model <- function(time, state, parameters) {
  with(as.list(c(state, parameters)), {
    dS <- -beta * S * I
    dE1 <- beta * S * I - sigma * E1
    dE2 <- sigma * E1 - gamma * E2
    dI <- gamma * E2 - lambda * I
    dR <- lambda * I
    return(list(c(dS, dE1, dE2, dI, dR)))
  })
}

par(las=F)

# Initial state and parameters
initial_state <- c(S = 999, E1 = 1, E2 = 0, I = 0, R = 0)
parameters <- c(beta = 0.001, sigma = 0.1, gamma = 0.1, lambda = 0.1)
times <- seq(0, 150, by = 1)

# Solve the model
output <- ode(y = initial_state, times = times, func = seeir_model, parms = parameters)

# Convert output to a data frame
output_df <- as.data.frame(output)

# Reshape for ggplot2
output_melted <- melt(output_df, id.vars = "time")

# Plot using ggplot2
ggplot(output_melted, aes(x = time, y = value, color = variable)) +
  geom_line() +
  labs(x = "Time", y = "Number of Individuals", color = "Compartment") +
  ggtitle("SEIR Model") +
  theme_minimal()
```

```{r}
# Initial state and parameters
initial_state <- c(S = 999, E1 = 1, E2 = 0, I = 0, R = 0)
parameters <- c(beta = 0.001, sigma = 0.1, gamma = 0.01, lambda = 0.1)
times <- seq(0, 1000, by = 1)

# Solve the model
output <- ode(y = initial_state, times = times, func = seeir_model, parms = parameters)

# Convert output to a data frame
output_df <- as.data.frame(output)

# Reshape for ggplot2
output_melted <- melt(output_df, id.vars = "time")

# Plot using ggplot2
ggplot(output_melted, aes(x = time, y = value, color = variable)) +
  geom_line() +
  labs(x = "Time", y = "Number of Individuals", color = "Compartment") +
  ggtitle("SEIR Model") +
  theme_minimal()
```

